name: mlnotes
description: Machine Learning Notes
url: http://mlnotes.com
markdown: rdiscount
permalink: /:year/:month/:day/:title.html
author: hanfeng
email: me@mlnotes.com
pygments: true
safe: true
paginate: 16
auto: true
keywords: [Machine Learning,机器学习,Algorithm,算法,Math,数学,Distributed,分布式]
github: mlnotes
duoshuo: mlnotes
bshare: 41a98299-efe8-4d9c-8775-b7de762a29da
excerpt_separator: "" # to workaround highlight tag was never closed
